spring:
  application:
    name: xme-salute-ai

  ai:
    openai:
      base-url: http://localhost:5005/v1  # LLM
      api-key: dummy-key
      chat:
        options:
          model: WizardLM-7B-GGML
      
server:
  port: 8080   # port

app:
  llm:
    provider: docker