spring:
  application:
    name: xme-salute-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:4b
          temperature: 0.7

server:
  port: 8080   # port