spring:
  application:
    name: xme-salute-ai

  datasource:
    url: jdbc:postgresql://localhost:5432/springai
    username: postgres
    password: mysecretpassword

  ai:
    openai:
      base-url: http://localhost:12434/engines
      api-key: dummy-key
      chat:
        options:
          model: ai/gemma3:1B-Q4_K_M
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
        initialize-schema: true  # crea automaticamente la tabella per gli embedding
        table-name: vector_store
server:
  port: 8080   # port

app:
  llm:
    provider: docker