spring:
  application:
    name: xme-salute-ai

  datasource:
    url: jdbc:postgresql://localhost:5432/postgresml
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      base-url: http://localhost:12434/engines
      api-key: dummy-key
      chat:
        options:
          model: ai/gemma3:1B-Q4_K_M
    vectorstore:
      pgvector:
        table-name: vector_store
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384
        max-document-batch-size: 10000
        initialize-schema: true  # crea automaticamente la tabella per gli embedding

server:
  port: 8080   # port

app:
  llm:
    provider: docker
  postgresml:
    embedding-function: pgml_embed_text
    model-name: mixedbread-ai/mxbai-embed-large-v1
  pdf:
    folder: src/main/resources/doc